### ISSUE TITLE
Кнопка выхода.

### ISSUE THREAD

**Issue by trynottosmile** [SPbSUPractiseTeam/Quality_rating_for_SPbSU_courses#18]
Нужно настроить работу кнопки выхода,сейчас совсем не работает.

**Comment by trynottosmile** [comment]
Работает в Google Chrome,Mozila

**Comment by RikeVoltz** [comment]
UPD: Работает в Yandex Browser 18.10, Opera 56, Chrome 70, Safari 11.1.1.
