### ISSUE TITLE
Регистрация.

### ISSUE THREAD

**Issue by trynottosmile** [SPbSUPractiseTeam/Quality_rating_for_SPbSU_courses#19]
Пока неизвестно нужна ли нам функция регистрации,возможно мы будем использовать что-то вроде st.
Если регистрация реализуется на нашей стороне - то изменить страницу регистрации:Одна узкая колонка крайне сложно отображается.

**Comment by trynottosmile** [comment]
Ответили что регистрация должна происходить на нашей стороне.Было бы неплохо сделать возможность подвердить аккаунт через почту.Чтобы слишком часто не регистрировались можно добавить капчу.

**Comment by RikeVoltz** [comment]
Добавлена reCaptcha v2, добавлено подтверждение регистрации по email.

**Comment by RikeVoltz** [comment]
UPD: Сейчас на отправителе писем стоит мой зареганный аккаунт с "паролем для приложения". Данный вопрос необходимо будет уточнять дальше, если проект будут переносить куда-либо.

**Comment by RikeVoltz** [comment]
Ширина формы регистрации также пофикшена
