### ISSUE TITLE
Удаление загрузок,удаление курсов и изменение названия курсов.

### ISSUE THREAD

**Issue by trynottosmile** [SPbSUPractiseTeam/Quality_rating_for_SPbSU_courses#22]
Если методист загрузил не те логи ,опечатался в названии или если курс переименовали,то ему ,возможно,понадобится изменить следующие данные:
1.Название курса.
2.Удалить выбранную загрузку.
3.Удалить весь курс целиком.

**Comment by RikeVoltz** [comment]
Реализована возможность редактирования названия курса (нажатием на кнопку 🖉), удаления курса(нажатием на кнопку 🗙) и удаления отдельного лога(нажатием на кнопку "Удалить загрузку" на странице загрузки). Кнопка  "Удалить загрузку" появляется только при количестве загруженных логов > 1, в ином случае нужно воспользоваться кнопкой удаления курса.
