### ISSUE TITLE
Подправить кнопку добавления курса.

### ISSUE THREAD

**Issue by trynottosmile** [SPbSUPractiseTeam/Quality_rating_for_SPbSU_courses#25]
Когда не добавлено ни одного курса - кнопка чуть ниже чем хотелось бы
![screenshot from 2018-11-24 17-57-30](https://user-images.githubusercontent.com/33633636/48969673-e9f49d00-f012-11e8-8283-c4897e4ea61d.png)

**Comment by RikeVoltz** [comment]
FIxed
