### ISSUE TITLE
кнопка "войти" на странице регистрации

### ISSUE THREAD

**Issue by IrinaTsekhanovich** [SPbSUPractiseTeam/Quality_rating_for_SPbSU_courses#37]
На странице регистрации нужно сделать кнопку "войти", чтобы пользователь мог сразу перейти в окно входа, не переходя на главную страницу

**Comment by RikeVoltz** [comment]
На всех страницах с какими-то сообщениями (Об активации email, о просьбе перейти по ссылке, чтобы активировать email, etc., добавлена кнопка "Войти на сайт"
