### ISSUE TITLE
внешний вид лого+надпись

### ISSUE THREAD

**Issue by IrinaTsekhanovich** [SPbSUPractiseTeam/Quality_rating_for_SPbSU_courses#38]
надпись "система ..." не видна

![image](https://user-images.githubusercontent.com/43197316/49502743-cf2dee00-f886-11e8-91b4-9ac693a10e3e.png)
![image](https://user-images.githubusercontent.com/43197316/49503054-904c6800-f887-11e8-80e7-f3f91e21b266.png)

**Comment by trynottosmile** [comment]
#34  сюда же

**Comment by RikeVoltz** [comment]
В major update шрифты сделаны отзывчивыми к размеру экрана - сейчас надпись должна вмещаться корректно
