### ISSUE TITLE
внешний вид сообщения с завершением регистрации

### ISSUE THREAD

**Issue by IrinaTsekhanovich** [SPbSUPractiseTeam/Quality_rating_for_SPbSU_courses#39]
сделать без горизонтальной прокрутки, все сообщение должно помещаться на одной странице
![image](https://user-images.githubusercontent.com/43197316/49502851-0f8d6c00-f887-11e8-8384-7e96ce225c00.png)
![image](https://user-images.githubusercontent.com/43197316/49502876-1a480100-f887-11e8-8b63-ea48709b8297.png)

**Comment by RikeVoltz** [comment]
Fixed, само сообщение перенесено в центр экрана
