### ISSUE TITLE
выяснить, почему не загружаются новые логи

### ISSUE THREAD

**Issue by IrinaTsekhanovich** [SPbSUPractiseTeam/Quality_rating_for_SPbSU_courses#41]
Ошибка не в препроцессинге.
Если сейчас ошибка сохраняется из-за ограничения памяти, продумать, сколько памяти может потребоваться для системы, чтобы не было таких ошибок.

**Comment by trynottosmile** [comment]
память для системы = кол-во пользователей * кол-во загружаемых логов * средний объем памяти после обработки одного лога.
Сейчас нужно сконцентрироваться только на работоспособности приложения.

**Comment by RikeVoltz** [comment]
Ошибки с некоторыми логами (such as ACADRU и BIOINF) именно в модулях, что подтверждается записями логов.
ACADRU: ```json.decoder.JSONDecodeError: Invalid control character at: line 1 column 14884 (char 14883) - ошибка означает примерно то, что модуль создает некорректный json, который не парсится стандартным python-овским json.load.```
BIOINF: ```...line 76, in set_video_review
    review_intervals[i] += 1
IndexError: list index out of range```
Что означает, что падает именно модуль видео.
Лог PHYSNU отрабатывает корректно как на загрузке нового курса, так и на загрузке нового лога.
@trynottosmile выше отметил верный способ подсчёта необходимого количества памяти.
На данный момент dev-сайт ограничен ``` 512.0 MB quota```
Ишью стоит переадресовать data-analysts, здесь я его закрываю, ибо ошибки в работе сервера здесь нет - протестил ещё раз.
