### ISSUE TITLE
подписи к значкам

### ISSUE THREAD

**Issue by IrinaTsekhanovich** [SPbSUPractiseTeam/Quality_rating_for_SPbSU_courses#42]
сделать всплывающие подписи к значкам карандаш и крестик (при наведении мышкой на значок) - что будет происходить при нажатии на тот или иной значок?

![image](https://user-images.githubusercontent.com/43197316/49503684-14ebb600-f889-11e8-9f94-347006ad0a55.png)

**Comment by RikeVoltz** [comment]
Сделаны всплывающие подписи: "Изменить название курса" и "Удалить курс"
