### ISSUE TITLE
сделать переход по ссылке в новой вкладке

### ISSUE THREAD

**Issue by IrinaTsekhanovich** [SPbSUPractiseTeam/Quality_rating_for_SPbSU_courses#43]
При нажатии на какую-либо лекцию в курсе (например, физика), открывается платформа открытое образование в той же вкладке, где была система анализа онлайн-курсов. Было бы хорошо сделать, чтобы платформа открытое образование открывалась в новой вкладке, чтобы не терялась наша система.

**Comment by RikeVoltz** [comment]
@trynottosmile Ты забыл про ```target=_blank```. 
Теперь ссылки открываются в новой вкладке
